### ISSUE TITLE
BoosterBot moves to Alliance Tab and breaks continuously

### ISSUE THREAD

**Issue by Avrizinth** [little-fort/booster-bot#76] opened 2024-11-15 18:30 UTC
This has been happening for about 7 or 8 days.  The bot will finish a match, and move to the alliance tab (even without a single active alliance quest) and just stay on that tab forever.

**Comment by snaptools2023** [comment] 2024-11-15 22:35
This is a duplicate of #74

**Comment by little-fort** [comment] 2024-11-17 00:03
Hi, please try again with the latest release and let me know if you are still encountering issues: 

https://github.com/little-fort/booster-bot/releases/tag/v1.5.1

**Comment by Avrizinth** [comment] 2024-11-17 06:15
The issue appears to be resolved.

**Closed** 2024-11-17 06:55 UTC
